import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const neueHaasBold = localFont({
  src: "./fonts/NeueHaasDisplayBold.ttf",
  variable: "--font-neueHaasBold",
  // weight: "100 900",
});

const neueHaasLight = localFont({
  src: "./fonts/NeueHaasDisplayLight.ttf",
  variable: "--font-neueHaasLight",
  weight: "100 500 900",
})

const neueHaasMedium = localFont({
  src: "./fonts/NeueHaasDisplayMediu.ttf",
  variable: "--font-neueHaasMedium",
  weight: "100 500 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${neueHaasLight.variable} ${neueHaasBold.variable} ${neueHaasMedium.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
